# Generated by Django 5.0.4 on 2024-05-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('KitabPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BabPost', to='api.kitabpost')),
            ],
        ),
        migrations.CreateModel(
            name='FasalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('KitabPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FasalPost', to='api.kitabpost')),
            ],
        ),
    ]
